### ISSUE TITLE
Data being reversed

### ISSUE THREAD

**Issue by sapphire-sandcastles** [iris-edu/SAC2mseed#2]
Hi, 
I am currently using this tool to convert data from the SAC format to the MSEED format (as is intended by the program). However, when comparing the seismograms of the SAC data to the mseed data, it would appear that the data is somehow being reversed. For example the arrival of the waves is reversed compared to the order they should arrive in.

Is this to do with the endianess of the data in the sac file? If so do i have to set an option to change how the file is converted to mseed?

Thanks C

**Comment by chad-earthscope** [comment]
Hi @Calum-J-O.

I presume you are describing an inversion in amplitude.  Regardless, there is no know reversing in the converter.

One thought: is the SCALE header in the sac files set to a negative number?  If so perhaps your SAC reader is applying the scaling factor and inverting the amplitude.

If this does not explain your observations can you gzip one of the SAC files and share it with me?

**Comment by sapphire-sandcastles** [comment]
Hi, 
Thanks for your quick response to my issue. 
Sorry, I should have been more clear. What I meant was that the time of wave arrival has been inverted. So when plotting the MSEED format of the data, the P waves are now the last to arrive on the seismogram.

Below I have attached both the SAC and MSEED versions of the file (gzipped) along with 2 screenshots. Screenshot_1.png.gz shows how the data should be (taken from [here](http://geoserver.iris.edu/node/378682) - the seismogram in question is the 2nd in the list) and Screenshot_2.png.gz shows my "time inverted" version of the data (that has been produced using the MSEED file provided).

Thanks Calum  

[1803292127KMTH.mseed.gz](https://github.com/iris-edu/sac2mseed/files/3094316/1803292127KMTH.mseed.gz)
[1803292127KMTH.sac.gz](https://github.com/iris-edu/sac2mseed/files/3094317/1803292127KMTH.sac.gz)
[Screenshot_1.png.gz](https://github.com/iris-edu/sac2mseed/files/3094318/Screenshot_1.png.gz)
[Screenshot_2.png.gz](https://github.com/iris-edu/sac2mseed/files/3094319/Screenshot_2.png.gz)

------------------------------------
EDIT
------------------------------------
This issue only occurs on certain files I download from the IRIS platform!

**Comment by chad-earthscope** [comment]
@Calum-J-O Screenshot_2.png clearly shows the time axis of the plot going backwards in time.  Seems to be an issue with whatever is creating that plot and not the actual data itself.

**Comment by chad-earthscope** [comment]
Closing without confirmation.
