### ISSUE TITLE
miniSEED strangely time shifted

### ISSUE THREAD

**Issue by vpreatoni** [iris-edu/SAC2mseed#5]
sac2mseed version 1.12
Ubuntu Server 20.04
Kernel 5.4.0-84-generic

Command used to invoke sac2mseed:
`sac2mseed -e 10 AGS_HHE_VV_CP_20210101000000-20210102000000.sac`

After converting a SAC file to miniSEED, and opening both files on Swarm, miniSEED is time shifted (to the past) by 3h 26m.
At first I taught it was a time-zone issue, as my locale is UTC-3. But that 26min shift is very strange.

I attach the SAC file as extracted from Winston Wave Server, also the mseed file, and a Swarm screen capture showing difference.

[AGS_HHE_VV_CP_20210101000000-20210102000000.sac.zip](https://github.com/iris-edu/sac2mseed/files/7164930/AGS_HHE_VV_CP_20210101000000-20210102000000.sac.zip)

[AGS_HHE_VV_CP_20210101000000-20210102000000.mseed.zip](https://github.com/iris-edu/sac2mseed/files/7164921/AGS_HHE_VV_CP_20210101000000-20210102000000.mseed.zip)

![swarm](https://user-images.githubusercontent.com/49730193/133329804-57fad757-d129-4e8c-920c-e8aed63deacc.png)

**Comment by chad-earthscope** [comment]
@vpreatoni thank you very much for reporting this and providing test data!

The cause is a serious bug in the converter and a new release is available with a fix: https://github.com/iris-edu/sac2mseed/releases/tag/v1.13

**Comment by vpreatoni** [comment]
Thanks a lot! just cloned new release and working perfectly now.
